### PR TITLE
Sign the License

### PR DESCRIPTION
**Pull request by unixtensor**
Licenses are useless without signature

### CODE REVIEW

**Comment by kyuiki** [comment]
Ah! :D Thank you for reminding me that. I thought it's already signed when generated. Also nice to meet you again!

**Comment by unixtensor** [comment]
Ayee

**Comment by kyuiki** [comment]
> Ayee

x3 How are you btw! Long time no see

**Comment by unixtensor** [comment]
> > Ayee
> 
> x3 How are you btw! Long time no see

Life'ing

**Comment by kyuiki** [comment]
> > > Ayee
> > 
> > 
> > x3 How are you btw! Long time no see
> 
> Life'ing

Damn very relatable. Working on winning on life

**Comment by unixtensor** [comment]
> > > > Ayee
> > > 
> > > 
> > > x3 How are you btw! Long time no see
> > 
> > 
> > Life'ing
> 
> Damn very relatable. Working on winning on life

Wanna contact again?

**Comment by unittensor** [comment]
I was a horrible person and never forgot what I did, I dont make enemies; I was in a really bad mental state and never wanna look back to it/what i done

**Comment by kyuiki** [comment]
> I was a horrible person and never forgot what I did, I dont make enemies; I was in a really bad mental state and never wanna look back to it/what i done

Aww x3 It's alright! I already forgived you and leave the past. It's the new beginning now x3 No more past sadness, Also yes we can still contact again ^^. Telegram?

**Comment by kyuiki** [comment]
I saw you viewing my telegram, so yes you can contact me ^^

**Pull request merged**
